apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-api-py
  namespace: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-api-py
  template:
    metadata:
      labels:
        app: sample-api-py
    spec:
      containers:
      - name: sample-api-py
        image: mathstronautslearn/sample-api-py:1.0.0
        imagePullPolicy: Always
        volumeMounts:
        - name: sample-api-py-config
          mountPath: /app/src/configs/config.yaml
          subPath: config.yaml
          readOnly: true
        ports:
        - containerPort: 8000
      volumes:
      - name: sample-api-py-config
        configMap:
          name: sample-api-py