apiVersion: v1
kind: Service
metadata:
  name: sample-portal-py
  namespace: www
spec:
  selector:
    app: sample-portal-py
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: ClusterIP